### ISSUE TITLE
Code blocks metadata translated incorrectly

### ISSUE THREAD

**Issue by faern** [livioribeiro/cargo-readme#12]
If I annotate the crate docs with, for example, "no_run" to make the doctest not run:
```rust
//! ```rust,no_run
//! // My code
//! ```
```
It is translated, incorrectly, into:

    ```rust
    // My code
    ```rust

That last "rust" should not be there :)

**Comment by livioribeiro** [comment]
Fixed!

Just remember, you do not need to use `rust,no_run`, simply use `no_run`.

Thanks and keep rusting!

**Comment by faern** [comment]
Yes, I managed to go around it by only specifying `no_run`, but it's still good if `cargo-readme` is able to handle `rust,no_run` since it's a valid way to write it.

Great! Very fast fix 👌  Thanks for a very helpful tool!
