### ISSUE TITLE
Add crate name as title

### ISSUE THREAD

**Issue by flosse** [livioribeiro/cargo-readme#2]
In order to add the `# crate-name` I have to use a template but in most cases I'd be happy to just use a flag like `cargo readme --add-name-as-title`.
And the same thing could be used for sections like the license. E.g. `cargo readme --add-license-section` would take the `license` property from the `Cargo.toml` and add a section like
```
## License
This project is licensed under the {{license}} license.
```

Just some ideas you might take for a next release :)

**Comment by livioribeiro** [comment]
Nice! I'll try to work on it.
If you have more ideas please keep em coming.
Thanks!
