### ISSUE TITLE
An empty readme on v3.1.1

### ISSUE THREAD

**Issue by RazrFalcon** [livioribeiro/cargo-readme#25]
After updating to the v3 branch `cargo-readme` stopped working. The `{{readme}}` section is being replaced with nothing. 

Here is the test [crate](https://github.com/RazrFalcon/svgtypes). I'm using `.tpl`.

**Comment by RazrFalcon** [comment]
Looks like it doesn't like the license comment.

**Comment by otavio** [comment]
PR #23 should fix it.
