### ISSUE TITLE
Option to pull in struct/etc comments for documentation?

### ISSUE THREAD

**Issue by leeola** [livioribeiro/cargo-readme#37]
In binaries, I often use a configuration struct (via StructOpt) and all fields, data types for the configuration are properly commented on the structure(s) themselves. It would be great if `cargo readme` would pull documentation from more than just the file header. Thoughts?

Example:

```
//! Some file documentation

/// The configuration for the binary.
///
/// foo
#[derive(StructOpt, Debug)]
pub struct Config {
  /// Some port value.
  ///
  /// bar
  #[structopt(long, env = "PORT", default_value = "5051")]
  port: u16,
}
```

Might render to something like:

```
# Some file documentation

## The configuration for the binary.
foo

### Some port value
bar
```

Think this would be too difficult to "get right"? The only workaround I can think of is to copy the idiomatic documentation on the struct into the module header.. which seems, wrong. Thoughts?

**Comment by livioribeiro** [comment]
This may not be too complex to implement, but I don't really know if it's worth adding to cargo-readme. I didn't even know you could place doc comments like that

I would need to take a deeper look at this, and right now I don't have much time available, sorry

**Comment by leeola** [comment]
No worries, closing issue. Thanks!
