### ISSUE TITLE
Obtain source file from Cargo.toml.

### ISSUE THREAD

**Issue by Sean1708** [livioribeiro/cargo-readme#4]
Currently if no input is given you check for "src/lib.rs" or "src/main.rs", it would be quite good if you "Cargo.toml" instead.

First you could check for a library table like

```toml
[lib]
path = "..."
```

then check the firs binary in the `bin` list

```toml
[[bin]]
path = "..."
```

then finally fall back to checking "src". Or maybe a better idea would be to check "src" first then fall back to "Cargo.toml", since most projects will stick to using "src".

Having said that I'm not sure the extra complexity would be worth it considering `cargo readme --input=...` isn't that diificult to call, it would be nice though.

**Comment by livioribeiro** [comment]
That makes sense, I'll look into it.
