### ISSUE TITLE
`/*!…*/: inner block doc comment` will get empty readme?

### ISSUE THREAD

**Issue by biluohc** [livioribeiro/cargo-readme#9]
[Syntax Index](https://doc.rust-lang.org/book/syntax-index.html)

```sh
mxo@Deepin ~/D/c/doc_raw> cat src/lib.rs 
/*!
`DOC_RAW`

Doc from outer file
*/
mxo@Deepin ~/D/c/doc_raw> cat README.tpl 
{{readme}}⏎      
                                                                                                                   
mxo@Deepin ~/D/c/doc_raw> cargo readme  
# doc_raw

mxo@Deepin ~/D/c/doc_raw> 
```

**Comment by livioribeiro** [comment]
I hadn't anticipate multiline doc comments so `cargo-readme` is not aware of them. Isn't recommended to use single line comments? Anyway, I'll take a look at that.

Thanks for reporting this and good rusting.

**Comment by biluohc** [comment]
Thanks you very much,
block document comments are easier to maintain than line document comments.
after all, don't need to add "/ /!" for every line.

**Comment by livioribeiro** [comment]
Support for multiline doc comments landed on master a couple days ago.

I am making a lot of changes, but I hope I can make a release next week.
